#ifndef MI_STATE_H
#define MI_STATE_H

#include "mi_types.h"
#include "mi_rs485_dma_shared.h"
#include <stdbool.h>
#include <stdint.h>
#include <math.h>

/* Handles generated by CubeMX */
extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim16;
extern UART_HandleTypeDef huart2;
extern DMA_HandleTypeDef hdma_usart2_rx;

/* Shared runtime state */
extern mi_frame_parser_t g_parser;
extern mi_settings_t  g_settings;
extern mi_commands_t  g_cmd;
extern mi_telemetry_t g_tel;

extern uint32_t last_packet_tick;
extern bool hardware_comms_ok;
extern bool handshake_done;

extern volatile uint32_t dbg_main_rx_count;
extern volatile uint32_t dbg_parser_ok_count;
extern volatile uint32_t dbg_type_write_param_count;
extern volatile uint32_t dbg_crc_fail_count;
extern volatile uint16_t dbg_last_n;
extern volatile uint16_t dbg_last_crc_calc;
extern volatile uint16_t dbg_last_crc_recv;

extern volatile uint8_t  P00;
extern volatile uint8_t  P01;
extern volatile uint32_t P10;
extern volatile uint32_t P11;
extern volatile uint8_t  P12;
extern volatile uint8_t  P20;
extern volatile uint8_t  P21;
extern volatile uint8_t  P35;
extern volatile uint8_t  P42;
extern volatile uint8_t  P43;
extern volatile uint8_t  P44;
extern volatile uint16_t P45;
extern volatile bool params_locked;

extern volatile bool  cmd_ligar_motor;
extern volatile float cmd_frequencia_alvo;
extern volatile float f_atual;
extern volatile uint32_t debug_isr_cnt;

extern volatile float ramp_inc_up;
extern volatile float ramp_inc_down;
extern volatile float inv_fs_2pi;
extern volatile uint32_t current_arr;
extern volatile float amp_max_atual;
extern volatile float freq_ISR;

extern uint32_t backup_P10;
extern uint32_t backup_P11;
extern uint8_t  backup_P12;
extern uint8_t  backup_P20;
extern uint8_t  backup_P21;
extern uint8_t  backup_P35;
extern uint8_t  backup_P42;
extern uint8_t  P20_run;
extern uint8_t  P21_run;
extern uint32_t P10_run;
extern uint32_t P11_run;
extern bool     last_motor_state;
extern uint8_t  last_P42;
extern float theta_u;
extern float theta_v;
extern float theta_w;
extern const float MI_TWO_PI;

extern volatile uint32_t P30;
extern volatile uint32_t P31;
extern volatile uint8_t  P32;
extern volatile uint8_t  P33;
extern volatile uint8_t  P51;
extern volatile uint8_t  P80;
extern volatile uint8_t  P81;
extern volatile uint8_t  P82;
extern volatile uint32_t P83;
extern volatile uint32_t P84;
extern volatile uint8_t  P85;
extern volatile uint8_t  P86;

extern bool remote_system_on;
extern bool remote_start_latched;
extern bool remote_bomba_cmd;
extern bool remote_swing_cmd;
extern bool remote_exaustao_cmd;
extern mi_dreno_state_t remote_dreno_status;
extern bool motor_reverse;

extern uint32_t sensor_delay_counter;
extern uint32_t tsensor;
extern uint8_t  sensor_estavel;
extern uint8_t  sensor_ultimo_raw;
extern bool     motor_desligado;

extern GPIO_PinState ligar_bomba;
extern GPIO_PinState desligar_bomba;
extern GPIO_PinState ligar_swing;
extern GPIO_PinState desligar_swing;
extern GPIO_PinState ligar_dreno;
extern GPIO_PinState desligar_dreno;
extern GPIO_PinState ligar_motor_pin;
extern GPIO_PinState desligar_motor_pin;

extern volatile uint16_t sim_v_out;
extern volatile uint16_t sim_v_bus;
extern volatile uint16_t sim_i_out;
extern volatile uint8_t  sim_temp;

#endif
